name: Main Branch Workflow

on:
  push:
    branches:
      - main
    paths:
      - '.env'
      - 'settings/**'
permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::489994096722:role/oidc_assume_role-dev
          role-session-name: infraworkersession
          aws-region: us-west-2    

      # Add your additional setup steps here, e.g., installing dependencies, building, testing, etc.
      
      - name: Run Workflow on Changes
        run: |
          
            # Create a release and zip the files in the current repository
            version=$(git describe --tags --abbrev=0)
            zip_name="source-code-${version}.zip"
            zip -r $zip_name .

            # Print the list of files in the zip file (for verification purposes)
            unzip -l $zip_name

            # Upload the source code zip to S3 with a specific prefix
            aws s3 cp $zip_name s3://sehel/pass/$zip_name

            echo "Release created and source code zip uploaded to S3."

          
  
