name: Main Branch Workflow

on:
  push:
    branches:
      - main
  release:
    types:
      - created
    paths:
      - '.env'
      - 'settings/**'
permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::489994096722:role/oidc_assume_role-dev
          role-session-name: infraworkersession
          aws-region: us-west-2

      - name: Zip Files
        run: zip -r archive.zip ./*

      - name: Determine Branch
        id: determine_branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Check for Release
        if: github.event_name == 'release'
        run: aws s3 cp archive.zip s3://sehel/pass/

      - name: Execute Logic for Dev Branch
        if: steps.determine_branch.outputs.branch == 'dev'
        run: |
          # Your Bash script for the 'dev' branch
          echo "Executing logical code for the dev branch"
          
      # - name: Branch Error Message
      #   if: steps.determine_branch.outputs.branch != 'main' && steps.determine_branch.outputs.branch != 'dev'
      #   run: echo "Branch Error: Unknown branch '${{ steps.determine_branch.outputs.branch }}'"
