
name: Main Branch Workflow

on:
  push:
    branches:
      - main
    paths:
      - '.env'
      - 'settings/**'
permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::489994096722:role/oidc_assume_role-dev
          role-session-name: infraworkersession
          aws-region: us-west-2    

      # Add your additional setup steps here, e.g., installing dependencies, building, testing, etc.
      - name: Run Workflow on Changes
        run: |
         # Get the commit hash of the previous commit
         previous_commit=$(git rev-parse ${{ github.event.before }} || echo "4b825dc642cb6eb9a060e54bf8d69288fbee4904")

         # Check if .env or anything in the settings/ directory has changed
         if git diff --name-only $previous_commit | grep -E '(.env|settings/)'; then
          # Your workflow steps go here
           echo "Changes detected in .env or settings/ directory. Running workflow..."
             # Add your commands or scripts to be executed when changes are detected.
         else
           echo "No relevant changes detected. Skipping workflow execution."
         fi

  
